server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location = /openapi.yaml {
    add_header Cache-Control "public, max-age=300";
    default_type application/yaml;
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ $uri.html =404;
  }
}
